from .prompt_cycler_node import NODE_CLASS_MAPPINGS as PROMPT_CYCLER_NODE_CLASS_MAPPINGS
from .prompt_cycler_node import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_CYCLER_NODE_DISPLAY_NAME_MAPPINGS
from .wildcard_prompt_cycler_node import NODE_CLASS_MAPPINGS as WILDCARD_PROMPT_CYCLER_NODE_CLASS_MAPPINGS
from .wildcard_prompt_cycler_node import NODE_DISPLAY_NAME_MAPPINGS as WILDCARD_PROMPT_CYCLER_NODE_DISPLAY_NAME_MAPPINGS
from .smart_image_save import NODE_CLASS_MAPPINGS as SMART_IMAGE_SAVE_NODE_CLASS_MAPPINGS
from .smart_image_save import NODE_DISPLAY_NAME_MAPPINGS as SMART_IMAGE_SAVE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **PROMPT_CYCLER_NODE_CLASS_MAPPINGS,
    **WILDCARD_PROMPT_CYCLER_NODE_CLASS_MAPPINGS,
    **SMART_IMAGE_SAVE_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_CYCLER_NODE_DISPLAY_NAME_MAPPINGS,
    **WILDCARD_PROMPT_CYCLER_NODE_DISPLAY_NAME_MAPPINGS,
    **SMART_IMAGE_SAVE_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS'] 